# NOTE: repo needs a secrets PRIMER3_TOKEN that is a
# GitHub Personal Access Token (Fine Grained) with "Contents" Read Write
# permission
name: "Push New Tagged Version Docs Build"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "**docs**"  # Matches any branch that contains "docs"

  # Trigger on request (note this pushes to gh-pages and NOT gh-pages-test)
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Shallow clone is fine for docs
        persist-credentials: false  # Don't persist credentials as we use PRIMER3_TOKEN explicitly

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'  # Enable pip dependency caching

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "Cython==3.0.12" myst-parser sphinx sphinx_rtd_theme==2.0.0 sphinx-autodoc-typehints "setuptools>=67.1.0" wheel build
        python -m build
        python -m pip install -e .

    - name: Build documentation
      run: |
        cd docs/
        make html
        cd ..

    - name: Determine target branch
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        if [[ "$TAG_NAME" == v* || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
          echo "BRANCH_NAME=gh-pages" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=gh-pages-test" >> $GITHUB_ENV
        fi

    - name: Commit documentation changes to the target branch
      run: |
        git clone https://github.com/libnano/primer3-py.git --branch $BRANCH_NAME --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        branch: ${{ env.BRANCH_NAME }}
        directory: gh-pages
        github_token: ${{ secrets.PRIMER3_TOKEN }}
        force: true
